<a href="https://colab.research.google.com/github/deepakra0/tf/blob/Preprocessing/tf_BC_kp_binclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer/breast-cancer.data'
df = pd.read_csv(url
                 ,na_values='?'
                 ,names = ['recurrence', 'age', 'menopause', 'tumorsize', 'invnodes', 'nodecaps', 'degmalig', 'breast', 'breastquad' , 'irradiat']
)
df.dropna(inplace=True)

In [ ]:
ds = tf.data.Dataset.from_tensor_slices((dict(df.iloc[:,1:]), df.iloc[:,0].replace({'no-recurrence-events': 0, 'recurrence-events': 1})))
ds = ds.shuffle(buffer_size=len(df))
ds = ds.batch(10)

In [ ]:
ds_feature,ds_target = next(iter(ds))

In [ ]:
n1 = tf.keras.layers.experimental.preprocessing.Normalization()

In [ ]:
n1.adapt(ds_feature['degmalig'].numpy())

In [ ]:
l1 = n1(ds_feature['degmalig'])

In [ ]:
c1 = tf.keras.layers.experimental.preprocessing.StringLookup()

In [ ]:
c1.adapt(ds.map(lambda x,y:x['age']))  #(ds_feature['age'])

In [ ]:
c1(ds_feature['age'])

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 3, 3, 3, 2, 2, 2, 4, 4, 3])>

In [ ]:
e1 = tf.keras.layers.experimental.preprocessing.CategoryEncoding(num_tokens=c1.vocabulary_size())

In [ ]:
e1(c1(ds_feature['age'])) kkkplll

<tf.Tensor: shape=(10, 8), dtype=float32, numpy=
array([[0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>